<?php
// +----------------------------------------------------------------------
// | Created by PHPstorm: [ JRK丶Admin ]
// +----------------------------------------------------------------------
// | Copyright (c) 2019~2022 [LuckyHHY] All rights reserved.
// +----------------------------------------------------------------------
// | SiteUrl: http://www.luckyhhy.cn
// +----------------------------------------------------------------------
// | Author: DER <der1998@gmail.com>
// +----------------------------------------------------------------------
// | Date: 2020/7/30 0030
// +----------------------------------------------------------------------
// | Description: 熊掌推送
// +----------------------------------------------------------------------

namespace app\admin\controller\push;

use app\common\controller\AdminBaseController;
use app\common\library\Push;

class Xzhang extends AdminBaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @throws \think\Exception
     * @throws \think\exception\PDOException
     * @author: DER <der1998@gmail.com>
     * @name: xiongzhang
     * @describe:
     */
    public function xiongzhang()
    {
        $action = $this->request->post("action");
        $urls = $this->request->post("urls");
        $urls = explode("\n", $urls);
        $urls = array_unique(array_filter($urls));
        if (!$urls) {
            $this->error("URL列表不能为空");
        }

        $result = false;
        if ($action == 'urls') {
            $type = $this->request->post("type");
            if ($type == 'realtime') {
                $result = Push::init(['type' => 'xiongzhang'])->realtime($urls);
            } else {
                $result = Push::init(['type' => 'xiongzhang'])->history($urls);
            }
        } elseif ($action == 'del') {
            $result = Push::init(['type' => 'xiongzhang'])->delete($urls);
        }

        if ($result) {
            $data = Push::init()->getData();
            $this->success("推送成功", null, $data);
        } else {
            $this->error("推送失败：" . Push::init()->getError());
        }
    }

}